image: node:latest

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd server
    - npm install

test:
  stage: test
  tags:
  - docker
  script:
  - cd server
  - npm run test